---

domain: openfoodbrasil.com.br
rails_env: production

admin_email: frattezi@tremtec.com

mail_domain: openfoodnetwork.com.br

swapfile_size: 3G
unicorn_timeout: 120

certbot_domains:
  - openfoodbrasil.com.br
  - www.openfoodbrasil.com.br
